# Main system configuration for the "nixos" host.
#
# This file defines host-specific settings and ties all modules together.
# The hardware-configuration.nix next to this file is auto-generated by the
# NixOS installer — it knows your disk layout, CPU, kernel modules, and
# filesystems. DO NOT edit it manually.
#
# To apply changes after editing any file in this repo:
#   sudo nixos-rebuild switch --flake /etc/nixos/nixos-config#nixos
#
# Shorter alias (defined in home/radu.nix):
#   rebuild

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix    # Auto-generated — do not edit

    ../../modules/common.nix        # Locale, timezone, fonts, audio
    ../../modules/desktop.nix       # KDE Plasma 6, display manager, Wayland tools
    ../../modules/development.nix   # Compilers, debuggers, build tools
    ../../modules/gaming.nix        # Steam, Lutris, GameMode, RetroArch
    ../../modules/claude.nix        # Claude Desktop (via PR #89 fix branch)
    ../../modules/audio-visualizer.nix  # Audio visualizer widget dependencies
    # ../../modules/vm.nix          # QEMU/KVM guest tools — only needed in a VM
    # ../../modules/virtualbox.nix  # VirtualBox guest additions — only needed in a VM
  ];

  # ── Unfree packages ──────────────────────────────────────────────────────────
  nixpkgs.config.allowUnfree = true;
  nixpkgs.config.permittedInsecurePackages = [
    "electron-36.9.5"  # required by obsidian / vesktop
  ];

  # ── Overlays ──────────────────────────────────────────────────────────────────
  nixpkgs.overlays = [
    (final: prev: {
      # openldap's syncreplication test (test017) is timing-sensitive and fails
      # non-deterministically on nixos-unstable. Skip tests; the package itself is fine.
      openldap = prev.openldap.overrideAttrs (_: { doCheck = false; });
      # libreoffice-fresh CppunitTest_sd_export_tests fails in sandbox builds on
      # nixos-unstable (environment / font rendering differences). Package is fine.
      libreoffice-fresh = prev.libreoffice-fresh.overrideAttrs (_: { doCheck = false; });
    })
  ];

  # ── Kernel ───────────────────────────────────────────────────────────────────
  # Use the latest upstream kernel (Linux 7.x as of nixos-unstable April 2026).
  # The NVIDIA open module (nvidia.nix) supports this via open = true.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ── Bootloader ───────────────────────────────────────────────────────────────
  # systemd-boot for UEFI systems (standard on all modern hardware).
  # After install, run `efibootmgr` to verify the entry was created.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.efi.efiSysMountPoint = "/boot/efi";

  # ── Network ──────────────────────────────────────────────────────────────────
  networking.hostName = "nixos";
  # NetworkManager handles connections and integrates with KDE's network applet.
  networking.networkmanager.enable = true;

  # ── Firewall ─────────────────────────────────────────────────────────────────
  networking.firewall.enable = true;
  # Open extra ports as needed:
  # networking.firewall.allowedTCPPorts = [ 8080 3000 ];

  # ── SSH daemon ────────────────────────────────────────────────────────────────
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;    # Fine for a local VM
      PermitRootLogin        = "no";    # Never allow root SSH
    };
  };

  # ── Shell: zsh ───────────────────────────────────────────────────────────────
  # This registers zsh as a valid login shell in /etc/shells.
  # The per-user shell is set in the users block below.
  # The actual zsh configuration lives in home/radu.nix.
  programs.zsh.enable = true;

  # ── Users ─────────────────────────────────────────────────────────────────────
  # Passwords are set with `passwd radu` after first boot — never store them here.
  users.users.radu = {
    isNormalUser = true;
    description  = "Radu";
    shell        = pkgs.zsh;
    extraGroups  = [
      "wheel"           # sudo access
      "networkmanager"  # manage Wi-Fi / Ethernet without sudo
      "audio"           # direct ALSA audio access + JACK real-time limits
      "video"           # GPU and display device access
      "input"           # game controller / input device access
      "gamemode"        # allow gamemoderun to grant elevated priority
    ];
  };

  security.sudo.wheelNeedsPassword = true;

  # ── Global packages ───────────────────────────────────────────────────────────
  # Keep this minimal. User-facing tools belong in home/radu.nix where they
  # are tracked per-user and isolated from system changes.
  environment.systemPackages = with pkgs; [
    vim     # Last-resort editor before Home Manager activates
    wget
    curl
    git
    pciutils      # lspci — useful for checking GPU in the VM
    usbutils      # lsusb
    claude-code-bin  # Claude Code CLI (system-wide so desktop apps can find it)
  ];

  # ── Nix settings ──────────────────────────────────────────────────────────────
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
    trusted-users = [ "root" "radu" ];
    # Cap cores per build job. Default is all threads (16 on Ryzen 7 3700X),
    # which causes OOM when compiling large packages. 8 threads still fast.
    cores = 4;
    max-jobs = 1;
    # Redirect build sandboxes to the HDD so large source builds (plasma,
    # libreoffice, etc.) don't fill the root partition with 15-25 GB of
    # intermediate files. The daemon ignores TMPDIR set on the CLI — this
    # is the correct knob. Requires the HDD to be mounted before nix-daemon
    # starts; if it ever becomes unavailable, comment this out.
    substituters = [
      "https://cache.nixos.org"
      # nix-community.cachix.org removed: every substitute was rejected with
      # "not signed by any of the keys in trusted-public-keys", meaning their
      # signing key has changed. Re-add with the updated key once confirmed:
      #   curl -s https://nix-community.cachix.org/nix-cache-info
      # "https://nix-community.cachix.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      # "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCUSeBc="
    ];
  };

  # Auto garbage collection — removes unreferenced store paths weekly.
  # Keeps the last 14 days of generations so you can always roll back.
  nix.gc = {
    automatic = true;
    dates     = "weekly";
    options   = "--delete-older-than 14d";
  };

  # ── State version ─────────────────────────────────────────────────────────────
  # Tracks the NixOS release this system was first set up with.
  # Do NOT change this value after first boot — it guards certain stateful defaults.
  system.stateVersion = "24.11";
}
